name: Generate Systems Engineer Resume

on:
  push:
    branches: 
      - main
    tags:
       - '*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - title: "Systems Engineer Principal"
            latexfile: systems-engineer-principal-resume.tex
            id: "systems-engineer-principal"
          - title: "Systems Engineer Manager"
            latexfile: systems-engineer-manager-resume.tex
            id: "systems-engineer-manager"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        sparse-checkout: |
          ${{ matrix.latexfile }}

    - name: Restore TeX Live cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: /root/texlive
        key: texlive-cache-${{ matrix.id }}-${{ runner.os }}-${{ hashFiles('**/*') }}
        restore-keys: texlive-cache-${{ matrix.id }}

    - name: ${{ matrix.title }} latex2pdf
      if: ${{ hashFiles('systems-engineer-principal-resume.tex') != '' }}
      id: compile-latex-document
      uses: xu-cheng/latex-action@6549dc21effb2730855a1281407ecfcececc6c1b # 4.1.0
      continue-on-error: true
      with:
        root_file: ${{ matrix.latexfile }}
        docker_image: ghcr.io/xu-cheng/texlive-alpine@sha256:8b4a00b6a17ebe6b96dee107d82f0cb3eb40daf322f1e23809a9be26486963dd # 20260401
        extra_system_packages: "inkscape ghostscript"
        pre_compile: |
          echo "tlmgr conf: $(tlmgr conf)"
          echo "tlmgr conf texmf: $(tlmgr conf texmf)"          
          tlmgr option repository https://mirror.ctan.org/systems/texlive/tlnet
          tlmgr update --self
          if [ $? -ne 0 ]; then
            tlmgr option repository https://mirror.math.princeton.edu/pub/CTAN/systems/texlive/tlnet
            tlmgr update --self
          fi
          tlmgr option repository https://mirror.ctan.org/systems/texlive/tlnet
          tlmgr update --all
          if [ $? -ne 0 ]; then
            tlmgr option repository https://mirror.math.princeton.edu/pub/CTAN/systems/texlive/tlnet
            tlmgr update --all
          fi
        post_compile: "latexmk -c"

    - name: ${{ matrix.title }} upload PDF to the workflow tab
      if: ${{ hashFiles(format('{0}-resume.pdf', matrix.id)) != '' }}
      id: upload-workflow-tab
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ matrix.id }}-resume
        path: ${{ matrix.id }}-resume.pdf
        if-no-files-found: warn
